# Dependencies
markdown:         kramdown
pygments:         false

# Permalinks
permalink:        pretty

# Setup
title:            Ready router one
tagline:          ''
description:      'here are my network notes and cool life bits'
url:              https://blog.readyrouterone.com
baseurl: ""
sass:
  style: compressed
  sass_dir: _scss

author:
  name:           'Laura Alonso'
  url:            https://twitter.com/prettymeetswrld

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/coding-laura
