# Dependencies
markdown:         kramdown
highlighter:         false

# Permalinks
permalink:        pretty

# Setup
title:            READY ROUTER ONE
tagline:          'up/connected'
description:      'My little internet corner for network notes and life bits.'
url:              https://blog.readyrouterone.com
baseurl: ""
sass:
  style: compressed
  sass_dir: _scss
title_image:      favicon.png

author:
  name:           'Laura Alonso'
  url:            https://twitter.com/prettymeetswrld

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/coding-laura

plugins: [jekyll-paginate]

feed:
  path: feed.xml