# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            laura.
tagline:          'network tagline'
description:      'tinkering, labbing, sharing'
url:              https://blog.alonsolabs.com

author:
  name:           'Laura Alonso'
  url:            https://twitter.com/prettymeetswrld

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/coding-laura
